// In-game sound system. Uses Web Audio synthesis - no asset downloads, no
// licensing concerns, instant playback. Each sound is generated by an
// oscillator with a short envelope.
//
// Designed for the BlobRun game loop, which fires sound events at known
// game-state transitions (jump, land, pickup, combo, death). Calls are safe
// from any frame, including the inner sim loop - we throttle overlapping
// same-event sounds so a 4-token-per-frame pickup doesn't stack into a click.
//
// Persistence: mute state is stored in localStorage under "blob.audio.muted"
// so the user's choice survives reloads. Default = unmuted, but the first
// resume() must be triggered by a user gesture (browser autoplay policy).

const MUTE_KEY = "blob.audio.muted";

let ctx: AudioContext | null = null;
let master: GainNode | null = null;
let muted = false;
let initialised = false;

// Per-event throttle so a stream of pickups doesn't blow out the speakers
// or distort into noise. Each event gets a minimum gap in ms.
const lastFiredAt: Record<string, number> = {};
const throttleMs: Record<string, number> = {
  pickup: 40,
  jump: 80,
  land: 80,
  duck: 80,
  unduck: 80,
  combo: 120,
  death: 0,
};

function loadMutedFromStorage(): boolean {
  try {
    return localStorage.getItem(MUTE_KEY) === "1";
  } catch {
    return false;
  }
}

function saveMutedToStorage(m: boolean) {
  try {
    localStorage.setItem(MUTE_KEY, m ? "1" : "0");
  } catch { /* ignore */ }
}

// Lazy-init the AudioContext. Must be called from a user gesture the first
// time or browsers will leave it suspended. We attempt resume() too as a
// fallback for browsers that allow creation but require explicit resume.
function ensureCtx(): AudioContext | null {
  if (ctx) return ctx;
  if (typeof window === "undefined") return null;
  try {
    const Ctor: typeof AudioContext = (window as any).AudioContext ?? (window as any).webkitAudioContext;
    if (!Ctor) return null;
    ctx = new Ctor();
    master = ctx.createGain();
    master.gain.value = muted ? 0 : 0.35; // overall volume cap
    master.connect(ctx.destination);
  } catch {
    return null;
  }
  return ctx;
}

// Public init - call once on game mount, ideally from a click handler so
// the AudioContext starts in the running state.
export function initSound() {
  if (initialised) {
    // Resume in case browser suspended it (e.g. tab backgrounded).
    ctx?.resume().catch(() => { /* ignore */ });
    return;
  }
  initialised = true;
  muted = loadMutedFromStorage();
  const c = ensureCtx();
  if (c && c.state === "suspended") {
    c.resume().catch(() => { /* ignore */ });
  }
}

export function isMuted(): boolean {
  // Read fresh so toggle from another tab/window propagates if needed.
  return muted;
}

export function setMuted(m: boolean) {
  muted = m;
  saveMutedToStorage(m);
  if (master) master.gain.value = m ? 0 : 0.35;
}

export function toggleMuted(): boolean {
  setMuted(!muted);
  return muted;
}

// Core synth helper: tone + ADSR envelope, returns when sound finishes
// scheduling (doesn't block playback).
function tone(opts: {
  freq: number;
  type?: OscillatorType;
  duration?: number;       // total seconds
  attack?: number;         // seconds
  decay?: number;          // seconds
  sustain?: number;        // 0..1 fraction of peak
  release?: number;        // seconds
  peak?: number;           // 0..1 gain at peak
  endFreq?: number;        // optional pitch slide target
}) {
  const c = ensureCtx();
  if (!c || muted) return;
  const now = c.currentTime;
  const attack = opts.attack ?? 0.005;
  const decay = opts.decay ?? 0.04;
  const sustain = opts.sustain ?? 0.3;
  const release = opts.release ?? 0.08;
  const duration = opts.duration ?? 0.12;
  const peak = opts.peak ?? 0.6;
  const sustainTime = Math.max(0, duration - attack - decay - release);
  const endTime = now + attack + decay + sustainTime + release;

  const osc = c.createOscillator();
  osc.type = opts.type ?? "square";
  osc.frequency.setValueAtTime(opts.freq, now);
  if (opts.endFreq != null) {
    osc.frequency.exponentialRampToValueAtTime(Math.max(20, opts.endFreq), endTime);
  }

  const gain = c.createGain();
  gain.gain.setValueAtTime(0, now);
  gain.gain.linearRampToValueAtTime(peak, now + attack);
  gain.gain.linearRampToValueAtTime(peak * sustain, now + attack + decay);
  gain.gain.setValueAtTime(peak * sustain, now + attack + decay + sustainTime);
  gain.gain.linearRampToValueAtTime(0, endTime);

  osc.connect(gain);
  if (master) gain.connect(master);
  osc.start(now);
  osc.stop(endTime + 0.02);
}

// Short noise burst for impact-y sounds (death). Uses an offline-generated
// noise buffer fed through a sharp envelope.
function noise(opts: { duration?: number; peak?: number; lowpassFreq?: number }) {
  const c = ensureCtx();
  if (!c || muted) return;
  const duration = opts.duration ?? 0.3;
  const peak = opts.peak ?? 0.5;
  const lpf = opts.lowpassFreq ?? 2400;
  const now = c.currentTime;

  const buf = c.createBuffer(1, Math.ceil(c.sampleRate * duration), c.sampleRate);
  const data = buf.getChannelData(0);
  for (let i = 0; i < data.length; i++) data[i] = (Math.random() * 2 - 1);

  const src = c.createBufferSource();
  src.buffer = buf;

  const filter = c.createBiquadFilter();
  filter.type = "lowpass";
  filter.frequency.value = lpf;

  const gain = c.createGain();
  gain.gain.setValueAtTime(peak, now);
  gain.gain.exponentialRampToValueAtTime(0.001, now + duration);

  src.connect(filter); filter.connect(gain);
  if (master) gain.connect(master);
  src.start(now);
  src.stop(now + duration + 0.02);
}

function throttle(event: string): boolean {
  const min = throttleMs[event] ?? 0;
  const now = performance.now();
  const last = lastFiredAt[event] ?? -Infinity;
  if (now - last < min) return false;
  lastFiredAt[event] = now;
  return true;
}

// ── Public event API ───────────────────────────────────────────────────
// Each function is a no-op if muted or if the AudioContext failed to start.
// Throttled so spammy events (pickups, mash-jumps) don't distort.

export function sfxJump() {
  if (!throttle("jump")) return;
  // Rising blip: 440 -> 660 Hz.
  tone({ freq: 440, endFreq: 660, type: "square", duration: 0.08, peak: 0.5, attack: 0.002, decay: 0.02, sustain: 0.6, release: 0.04 });
}

export function sfxLand() {
  if (!throttle("land")) return;
  // Soft thud: low square, quick decay.
  tone({ freq: 180, endFreq: 120, type: "triangle", duration: 0.06, peak: 0.35, attack: 0.002, decay: 0.02, sustain: 0.4, release: 0.03 });
}

export function sfxDuck() {
  if (!throttle("duck")) return;
  tone({ freq: 220, endFreq: 140, type: "sine", duration: 0.07, peak: 0.4, attack: 0.002, decay: 0.02, sustain: 0.5, release: 0.04 });
}

export function sfxUnduck() {
  if (!throttle("unduck")) return;
  tone({ freq: 200, endFreq: 280, type: "sine", duration: 0.05, peak: 0.3, attack: 0.002, decay: 0.015, sustain: 0.5, release: 0.025 });
}

export function sfxPickup(comboLevel: number = 0) {
  if (!throttle("pickup")) return;
  // Pitch rises with combo so back-to-back pickups feel rewarding.
  const baseFreq = 880 + Math.min(comboLevel, 16) * 40;
  tone({ freq: baseFreq, endFreq: baseFreq * 1.5, type: "triangle", duration: 0.09, peak: 0.45, attack: 0.001, decay: 0.02, sustain: 0.5, release: 0.05 });
}

export function sfxCombo(comboLevel: number) {
  if (!throttle("combo")) return;
  // Two-note flourish - higher = louder/higher pitch.
  const root = 660 + Math.min(comboLevel, 12) * 30;
  tone({ freq: root, type: "triangle", duration: 0.08, peak: 0.4 });
  setTimeout(() => {
    tone({ freq: root * 1.5, type: "triangle", duration: 0.1, peak: 0.5 });
  }, 60);
}

export function sfxDeath() {
  if (!throttle("death")) return;
  // Detuned descending blip + filtered noise burst for the explosion.
  tone({ freq: 220, endFreq: 60, type: "sawtooth", duration: 0.4, peak: 0.55, attack: 0.002, decay: 0.05, sustain: 0.7, release: 0.3 });
  noise({ duration: 0.35, peak: 0.4, lowpassFreq: 1600 });
}

export function sfxBlockSealed(isWinner: boolean) {
  // Triumphant chord for the user's win; soft chime for everyone else.
  if (isWinner) {
    const c = ensureCtx(); if (!c) return;
    const notes = [523.25, 659.25, 783.99]; // C5, E5, G5
    notes.forEach((f, i) => setTimeout(() => {
      tone({ freq: f, type: "triangle", duration: 0.4, peak: 0.5, attack: 0.005, decay: 0.05, sustain: 0.7, release: 0.25 });
    }, i * 80));
  } else {
    tone({ freq: 880, type: "sine", duration: 0.18, peak: 0.25, attack: 0.005, decay: 0.04, sustain: 0.5, release: 0.12 });
  }
}